name: YKTFLOW Auto Update
on:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов
  workflow_dispatch: # Возможность запустить вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Deep Checker
        run: python scripts/full_check.py

      - name: Commit and Push
        run: |
          git config --global user.name "YKTFLOW-Bot"
          git config --global user.user "bot@yktflow.dev"
          git add configs/*
          git commit -m "Update nodes: $(date)" || exit 0
          git push
