name: Proxy Vacuum
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Scraper
        # Теперь он заходит в папку scripts и запускает checker.go
        run: go run scripts/checker.go

      - name: Push Results
        run: |
          git config --global user.name "YKT-Vacuum-Bot"
          git config --global user.email "bot@ykt.flow"
          git add configs/*.txt
          git commit -m "Auto-update configs $(date)" || exit 0
          git push
          
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add data/stats.json configs/*.txt
          git commit -m "Update stats and configs" || echo "No changes to commit"
          git push
